'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {usePathname} from 'next/navigation';
import {getStoredUser,logout} from '@/lib/api';
import {Icon} from '@/components/UI';

export default function AppShell({children}:{children:React.ReactNode}){
 const [u,setU]=useState<any>(null),[open,setOpen]=useState(false);const path=usePathname();
 useEffect(()=>{const f=()=>setU(getStoredUser());f();window.addEventListener('authchange',f);return()=>window.removeEventListener('authchange',f)},[]);
 useEffect(()=>setOpen(false),[path]);
 const nav=[['/products','Sản phẩm'],['/search','Tìm kiếm'],...(u?[['/wishlist','Yêu thích'],['/orders','Đơn hàng']]:[]),...((u&&(u.roleCode==='ADMIN'||u.roleCode==='STAFF'))?[['/admin','Quản trị']]:[])];
 return <><a className="skipLink" href="#main-content">Bỏ qua điều hướng</a><div className="utilityBar"><div className="utilityInner"><span>Dữ liệu sản phẩm, giá và tồn kho đồng bộ trực tiếp từ hệ thống</span><span>Website đồ gia dụng DATN</span></div></div><header className="siteHeader"><div className="topbar"><Link className="brand" href="/" aria-label="Nhà Tiện Nghi - Trang chủ"><span className="brandMark">N</span><span>NHÀ <b>TIỆN NGHI</b></span></Link><nav className="desktopNav" aria-label="Điều hướng chính">{nav.map(([href,label])=><Link key={href} className={path===href?'active':''} href={href}>{label}</Link>)}</nav><div className="actions"><Link href="/cart" className="iconTextBtn"><Icon name="cart" size={19}/><span>Giỏ hàng</span></Link>{u?<><Link href="/account" className="userChip"><span className="avatarDot">{String(u.fullName||'U').charAt(0).toUpperCase()}</span><span>{u.fullName}</span></Link><button className="ghost desktopOnly" onClick={logout}>Đăng xuất</button></>:<Link className="primary small desktopOnly" href="/login">Đăng nhập</Link>}<button className="mobileMenuBtn" aria-label={open?'Đóng menu':'Mở menu'} aria-expanded={open} onClick={()=>setOpen(v=>!v)}><Icon name={open?'close':'menu'}/></button></div></div>{open&&<div className="mobileNav"><nav>{nav.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav>{u?<><Link href="/account">Tài khoản</Link><button onClick={logout}>Đăng xuất</button></>:<Link href="/login">Đăng nhập</Link>}</div>}</header><main id="main-content">{children}</main><footer className="siteFooter"><div className="footerGrid"><div><Link className="brand footerBrand" href="/"><span className="brandMark">N</span><span>NHÀ <b>TIỆN NGHI</b></span></Link><p>Nền tảng thương mại điện tử đồ gia dụng. Nội dung sản phẩm hiển thị theo dữ liệu backend và database của dự án.</p></div><div><b>Mua sắm</b><Link href="/products">Tất cả sản phẩm</Link><Link href="/search">Tìm kiếm & lọc</Link><Link href="/cart">Giỏ hàng</Link></div><div><b>Tài khoản</b><Link href="/account">Hồ sơ cá nhân</Link><Link href="/orders">Đơn hàng</Link><Link href="/wishlist">Yêu thích</Link></div></div><div className="footerBottom">© 2026 Nhà Tiện Nghi · DATN Software Engineering</div></footer></>
}
