import type {ApiEnvelope} from './types';
const BASE=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8080/api';
export function getToken(){return typeof window==='undefined'?null:localStorage.getItem('accessToken')}
export function getStoredUser(){if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}}
export function isLoggedIn(){return !!getToken()}
export async function request<T>(path:string,init:RequestInit={}):Promise<T>{
 const h=new Headers(init.headers); const token=getToken(); if(token)h.set('Authorization',`Bearer ${token}`); if(init.body&&!h.has('Content-Type'))h.set('Content-Type','application/json');
 const r=await fetch(`${BASE}${path}`,{...init,headers:h,cache:'no-store'});
 if(!r.ok){let m=`Lỗi ${r.status}`;try{const e=await r.json();m=e.message||e.error||m}catch{} if(r.status===401&&typeof window!=='undefined'){localStorage.removeItem('accessToken');localStorage.removeItem('refreshToken');localStorage.removeItem('user')} throw new Error(m)}
 if(r.status===204)return undefined as T; return r.json();
}
export function unwrap<T>(v:T|ApiEnvelope<T>):T{return v&&typeof v==='object'&&'data' in (v as object)?(v as ApiEnvelope<T>).data:v as T}
export const api={
 products:(qs='')=>request(`/v1/products${qs}`), product:(id:number|string)=>request(`/v1/products/${id}`), categories:()=>request('/v1/categories'), brands:()=>request('/v1/brands'),
 cart:()=>request('/cart').then(unwrap), addCart:(productId:number,quantity=1)=>request('/cart/items',{method:'POST',body:JSON.stringify({productId,quantity})}).then(unwrap), updateCart:(id:number,quantity:number)=>request(`/cart/items/${id}`,{method:'PUT',body:JSON.stringify({quantity})}).then(unwrap), removeCart:(id:number)=>request(`/cart/items/${id}`,{method:'DELETE'}).then(unwrap), clearCart:()=>request('/cart',{method:'DELETE'}),
 wishlist:()=>request('/wishlist').then(unwrap), wishAdd:(id:number)=>request(`/wishlist/${id}`,{method:'POST'}).then(unwrap), wishRemove:(id:number)=>request(`/wishlist/${id}`,{method:'DELETE'}).then(unwrap), wishCheck:(id:number)=>request(`/wishlist/${id}/check`).then(unwrap),
 orders:()=>request('/orders?size=100'), order:(id:number)=>request(`/orders/${id}`), createOrder:(body:unknown)=>request('/orders',{method:'POST',body:JSON.stringify(body)}), cancelOrder:(id:number)=>request(`/orders/${id}/cancel`,{method:'PATCH'}),
 reviews:(id:number)=>request(`/reviews/product/${id}?size=50`).then(unwrap), myReviews:()=>request('/reviews/me?size=100').then(unwrap), createReview:(body:unknown)=>request('/reviews',{method:'POST',body:JSON.stringify(body)}).then(unwrap), updateReview:(id:number,body:unknown)=>request(`/reviews/${id}`,{method:'PUT',body:JSON.stringify(body)}).then(unwrap), deleteReview:(id:number)=>request(`/reviews/${id}`,{method:'DELETE'}).then(unwrap),
 me:()=>request('/users/me'), updateMe:(body:unknown)=>request('/users/me',{method:'PUT',body:JSON.stringify(body)}), changePassword:(body:unknown)=>request('/users/me/password',{method:'PUT',body:JSON.stringify(body)}), addresses:()=>request('/users/me/addresses'), addAddress:(body:unknown)=>request('/users/me/addresses',{method:'POST',body:JSON.stringify(body)}), updateAddress:(id:number,body:unknown)=>request(`/users/me/addresses/${id}`,{method:'PUT',body:JSON.stringify(body)}), deleteAddress:(id:number)=>request(`/users/me/addresses/${id}`,{method:'DELETE'}), defaultAddress:(id:number)=>request(`/users/me/addresses/${id}/default`,{method:'PUT'}),
 voucher:(code:string,orderAmount:number)=>request('/vouchers/validate',{method:'POST',body:JSON.stringify({code,orderAmount})}).then(unwrap), pay:(id:number)=>request(`/payments/vnpay/create/${id}`,{method:'POST'}),
 login:(body:unknown)=>request('/auth/login',{method:'POST',body:JSON.stringify(body)}), register:(body:unknown)=>request('/auth/register',{method:'POST',body:JSON.stringify(body)}), forgot:(email:string)=>request('/auth/forgot-password',{method:'POST',body:JSON.stringify({email})}), reset:(body:unknown)=>request('/auth/reset-password',{method:'POST',body:JSON.stringify(body)}),
 adminProducts:(qs='')=>request(`/v1/products/management${qs}`), saveProduct:(id:number|null,body:unknown)=>request(id?`/v1/products/${id}`:'/v1/products',{method:id?'PUT':'POST',body:JSON.stringify(body)}), deleteProduct:(id:number)=>request(`/v1/products/${id}`,{method:'DELETE'}),
 saveCategory:(id:number|null,body:unknown)=>request(id?`/v1/categories/${id}`:'/v1/categories',{method:id?'PUT':'POST',body:JSON.stringify(body)}), deleteCategory:(id:number)=>request(`/v1/categories/${id}`,{method:'DELETE'}), saveBrand:(id:number|null,body:unknown)=>request(id?`/v1/brands/${id}`:'/v1/brands',{method:id?'PUT':'POST',body:JSON.stringify(body)}), deleteBrand:(id:number)=>request(`/v1/brands/${id}`,{method:'DELETE'}),
 adminOrders:()=>request('/admin/orders?size=100'), adminOrderStatus:(id:number,status:string,note='')=>request(`/admin/orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status,note})}),
 inventory:()=>request('/v1/inventory?size=100'), adjustInventory:(productId:number,changeQty:number)=>request(`/v1/inventory/product/${productId}/adjust`,{method:'POST',body:JSON.stringify({productId,changeQty,reason:'ADJUSTMENT',referenceType:'MANUAL_CHECK'})}),
 vouchers:()=>request('/vouchers?size=100').then(unwrap), saveVoucher:(id:number|null,body:unknown)=>request(id?`/vouchers/${id}`:'/vouchers',{method:id?'PUT':'POST',body:JSON.stringify(body)}).then(unwrap), disableVoucher:(id:number)=>request(`/vouchers/${id}/disable`,{method:'PATCH'}).then(unwrap),
 adminReviews:()=>request('/admin/reviews?size=100').then(unwrap), reviewStatus:(id:number,status:string)=>request(`/admin/reviews/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}).then(unwrap),
 users:()=>request('/admin/users?size=100'), userStatus:(id:number,status:string)=>request(`/admin/users/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}), userRole:(id:number,roleCode:string)=>request(`/admin/users/${id}/role`,{method:'PATCH',body:JSON.stringify({roleCode})}), createStaff:(body:unknown)=>request('/admin/users',{method:'POST',body:JSON.stringify(body)})
};
export function saveAuth(a:any){localStorage.setItem('accessToken',a.accessToken);localStorage.setItem('refreshToken',a.refreshToken);localStorage.setItem('user',JSON.stringify(a.user));window.dispatchEvent(new Event('authchange'))}
export function logout(){localStorage.clear();window.dispatchEvent(new Event('authchange'));window.location.href='/'}
